### PR TITLE
Bugs from shaun

### LINKED ISSUE #42: Bugs- see full details
- [x] Cannot add game from search results if game doesn't have a duration
- [ ] Searching for game `#$%` doesn't yield error for user
- [x] You can a game more than once on your self
- [x] Game Nights are added despite error stating otherwise
- [x] Cannot create games
- [x] - Dashboard shows login button even if already logged in

## Other considerations ## 
- Should you be able add two game nights on the same night?
- If I am a visitor I don't understand why your links don't work, looks like your site is broken.
- Do we want a start time on a gamenight? 
- Should my list of games be sorted?
- If I have over 30 board games, can I search for one?

### PR DESCRIPTION
**Pull request by katemorris**
### Description

- Checks to see if the user in the session has that game already. We need to make sure this gets updated when a user adds a game to their shelf in the same session. 
- Adds a default duration if there is none. 
- Changes to use the user add game endpoint that receives the payload correctly on the BE
- Adds redirect on home if the user is logged in
- Fixes tests for the checking for if the user has the game or not. 
- Gameration fixed (column spacing). It's hacky but works. 

### Closes issue(s)
#42 

### Testing

All tested and passing

### Changes include
- [X] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

### Checklist
- [ ] I have written tests for this code (happy & sad)
- [ ] I have updated the Readme
- [X] I ran rubocop and fixed issues
- [X] I ran full test suite - all tests passing

### CODE REVIEW

File: app/controllers/users/games_controller.rb [hunk 1]
```diff
@@ -2,14 +2,26 @@ class Users::GamesController < ApplicationController
   before_action :is_user
 
   def create
-    response = UserFacade.add_game(params, current_user.id)
-    if response.status == 200
-      flash[:success] = 'Game added to your shelf!'
-      redirect_to dashboard_path
+    if has_game?(params[:name], session)
+      flash[:error] = 'You already have that game!'
```
Comment (ShaunDaneJames) [inline app/controllers/users/games_controller.rb:6]: Nice logic gate here!

File: app/controllers/home_controller.rb [hunk 2]
```diff
@@ -1,3 +1,5 @@
 class HomeController < ApplicationController
-  def index; end
+  def index
+    redirect_to dashboard_path if current_user
+  end
```
Comment (GregJMitchell) [inline app/controllers/home_controller.rb:4]: Nice Auth here

File: app/views/games/search/_search.html.erb [hunk 3]
```diff
@@ -1,11 +1,16 @@
...
+  <p>We can't find anything! Try again or add it below.</p>
+  <% else %>
   <table>
     <tr>
-      <th><h3 class="row ml-1">Game</h3></th>
-      <th><h3 class="mr-5">Duration</h3></th>
-      <th><h3>Add Game</h3></th>
+      <th style="min-width: 100px;"><h3 class="row ml-1">Game</h3></th>
+      <th style="min-width: 100px;"><h3 class="mr-5">Duration</h3></th>
+      <th style="min-width: 100px;"><h3>Add Game</h3></th>
```
Comment (GregJMitchell) [inline app/views/games/search/_search.html.erb:9]: I LOVE inline styling

**Review by ShaunDaneJames — APPROVED** [review]

**Review by GregJMitchell — APPROVED** [review]
